### PR TITLE
remove hardcoded errbot version, fixes #8

### LINKED ISSUE #8: Use up to date errbot version
In your `requirements.txt`, you hardcoded the version of `errbot` to `4.1.3`.

Is there a reason for doing so? 
If not, would you mind removing the version, or at least hardcode a newer one? (The most up to date is `4.3.3`.)

### PR DESCRIPTION
**Pull request by stefan2904**
Applies fix proposed in #8.

### CODE REVIEW

**Comment by rroemhild** [comment]
Hi, did you test this? I've had problems with upgrading the docker image to err version 4.2 and since no time to look it. Would be great if version 4.3 just work out of the box in this docker image.

**Comment by stefan2904** [comment]
The following works for me:

```
# docker run --rm --name errbot-cws -it -v /opt/errbot/demo:/srv -e TZ=Europe/Vienna stefan2904/docker-errbot:errbot-version-fix /app/venv/bin/run.sh -c /srv/cw.py -T
# docker attach errbot-cws
!about
This is Errbot version 4.3.3
```

Also works with the XMPP backend.

**Comment by stefan2904** [comment]
What are/were your problems with 4.3?

**Comment by rroemhild** [comment]
As far I remember I've had build problems with dependencies, but with the brand new version 4.2. I've never looked into updates since. Thanks for your time looking into this. I'll merge your PR.

**Pull request merged**
